// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSample(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeSample'](arg1, arg2);
}

export function BrowseLogFile() {
  return window['go']['main']['App']['BrowseLogFile']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function EnsurePythonEnv() {
  return window['go']['main']['App']['EnsurePythonEnv']();
}

export function GetBatchProgress() {
  return window['go']['main']['App']['GetBatchProgress']();
}

export function GetEnvStatus() {
  return window['go']['main']['App']['GetEnvStatus']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetPythonEnvReady() {
  return window['go']['main']['App']['GetPythonEnvReady']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetShowWizard() {
  return window['go']['main']['App']['GetShowWizard']();
}

export function IsLLMConfigured() {
  return window['go']['main']['App']['IsLLMConfigured']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function RerunProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RerunProject'](arg1, arg2, arg3, arg4);
}

export function RunBatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunBatch'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SetShowWizard(arg1) {
  return window['go']['main']['App']['SetShowWizard'](arg1);
}

export function TestLLM() {
  return window['go']['main']['App']['TestLLM']();
}

export function UpdateProjectCode(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectCode'](arg1, arg2);
}
