// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {pyenv} from '../models';

export function AnalyzeSample(arg1:string,arg2:string):Promise<model.GenerateResult>;

export function BrowseLogFile():Promise<model.LogFileSample>;

export function DeleteProject(arg1:string):Promise<void>;

export function EnsurePythonEnv():Promise<void>;

export function GetBatchProgress():Promise<model.BatchProgress>;

export function GetEnvStatus():Promise<pyenv.EnvStatus>;

export function GetProject(arg1:string):Promise<model.Project>;

export function GetPythonEnvReady():Promise<Record<string, any>>;

export function GetSettings():Promise<model.Settings>;

export function GetShowWizard():Promise<boolean>;

export function IsLLMConfigured():Promise<boolean>;

export function ListProjects():Promise<Array<model.Project>>;

export function OpenDirectory(arg1:string):Promise<void>;

export function RerunProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RunBatch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SetShowWizard(arg1:boolean):Promise<void>;

export function TestLLM():Promise<void>;

export function UpdateProjectCode(arg1:string,arg2:string):Promise<void>;
